"use strict";
const db=window.supabase.createClient("https://gtmngtweohixfeajljik.supabase.co","sb_publishable_MDNyO5yGhyYJz23QZS-CGw_b0ymShkF",{auth:{persistSession:true,autoRefreshToken:true,storage:localStorage,storageKey:"evolve-quest-healer-auth"}});
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const STAGES={new:"Novo lead",contacted:"Contatado",payment_sent:"Pagamento enviado",negotiation:"Negociação",customer:"Aventureiro ativo",not_interested:"Sem interesse"};
const ACTIVE_STAGES=["dashboard","checkpoint","feedback","progression"];let rows=[],profiles=new Map();
function wa(phone){let n=String(phone||"").replace(/\D/g,"");if(!n)return"";if((n.length===10||n.length===11)&&!n.startsWith("55"))n="55"+n;return`https://wa.me/${n}`}
function dateInput(v){if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toISOString().slice(0,10)}
function isActive(p){return !!(p&&p.role==="adventurer"&&p.account_status==="active"&&ACTIVE_STAGES.includes(p.journey_stage))}
async function auth(){const{data:{session}}=await db.auth.getSession();if(!session){location.href="/healer/login/";return false}const{data:p,error}=await db.from("profiles").select("role,account_status").eq("id",session.user.id).maybeSingle();if(error||!p||!["healer","admin"].includes(p.role)||p.account_status!=="active"){location.href="/healer/login/";return false}return true}
async function load(){if(!(await auth()))return;$("#status").textContent="Carregando CRM...";const{data:crm,error}=await db.from("adventurer_crm").select("*");if(error){console.error(error);$("#status").textContent="Não foi possível carregar o CRM.";return}const{data:active}=await db.from("profiles").select("id,full_name,preferred_name,email,phone,city,state,role,account_status,journey_stage,created_at").eq("role","adventurer").eq("account_status","active");const ids=new Set([...(crm||[]).map(x=>String(x.adventurer_id)),...(active||[]).map(x=>String(x.id))]);let ps=[];if(ids.size){const{data}=await db.from("profiles").select("id,full_name,preferred_name,email,phone,city,state,role,account_status,journey_stage,created_at").in("id",[...ids]);ps=data||[]}profiles=new Map(ps.map(p=>[String(p.id),p]));const cm=new Map((crm||[]).map(r=>[String(r.adventurer_id),r]));rows=[...ids].map(id=>{const p=profiles.get(id)||{},c=cm.get(id),a=isActive(p);return{adventurer_id:id,pipeline_stage:a?"customer":c?.pipeline_stage||"new",next_follow_up_at:c?.next_follow_up_at||null,notes:c?.notes||"",created_at:c?.created_at||p.created_at||null,isActive:a,last_contact_at:c?.last_contact_at||null,payment_options_sent_at:c?.payment_options_sent_at||null}});$("#status").textContent=`${rows.length} contatos no CRM`;metrics();render()}
function metrics(){const now=new Date();$("#mAll").textContent=rows.length;$("#mNew").textContent=rows.filter(r=>!r.isActive&&r.pipeline_stage==="new").length;$("#mContacted").textContent=rows.filter(r=>!r.isActive&&r.pipeline_stage==="contacted").length;$("#mNegotiation").textContent=rows.filter(r=>!r.isActive&&["payment_sent","negotiation"].includes(r.pipeline_stage)).length;$("#mActive").textContent=rows.filter(r=>r.isActive).length;$("#mOverdue").textContent=rows.filter(r=>r.next_follow_up_at&&new Date(r.next_follow_up_at)<now).length}
function opts(cur){return Object.entries(STAGES).map(([v,l])=>`<option value="${v}" ${v===cur?"selected":""}>${l}</option>`).join("")}
function render(){const q=($("#searchInput").value||"").toLowerCase(),type=$("#typeFilter").value,stage=$("#stageFilter").value;const f=rows.filter(r=>{const p=profiles.get(String(r.adventurer_id))||{},s=`${p.full_name||""} ${p.preferred_name||""} ${p.email||""} ${p.phone||""}`.toLowerCase();return(!q||s.includes(q))&&!(type==="lead"&&r.isActive)&&!(type==="active"&&!r.isActive)&&(!stage||r.pipeline_stage===stage)});if(!f.length){$("#crmList").innerHTML='<div class="empty">Nenhum contato encontrado.</div>';return}$("#crmList").innerHTML=f.map(card).join("");document.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>save(b.dataset.save))}
function card(r){const p=profiles.get(String(r.adventurer_id))||{},name=p.preferred_name||p.full_name||p.email||"Aventureiro",link=wa(p.phone),over=r.next_follow_up_at&&!r.isActive&&new Date(r.next_follow_up_at)<new Date();return`<article class="crm-card" data-card="${esc(r.adventurer_id)}"><div class="person"><div class="avatar">${esc(name.slice(0,2).toUpperCase())}</div><div><h3>${esc(name)}</h3><p>${esc(p.phone||"Telefone não informado")}${p.email?` · ${esc(p.email)}`:""}</p><div class="badges"><span class="badge ${r.isActive?"active":""}">${r.isActive?"AVENTUREIRO ATIVO":"LEAD"}</span>${over?'<span class="badge overdue">FOLLOW-UP VENCIDO</span>':""}</div></div></div><div class="crm-grid"><div class="field"><label>Etapa comercial</label><select data-field="pipeline_stage" ${r.isActive?"disabled":""}>${opts(r.pipeline_stage)}</select></div><div class="field"><label>Próximo follow-up</label><input type="date" data-field="next_follow_up_at" value="${dateInput(r.next_follow_up_at)}"></div><div class="field"><label>Observação comercial</label><textarea data-field="notes">${esc(r.notes)}</textarea><div class="save-state" data-state></div></div><div class="actions">${link?`<a class="btn secondary wa" href="${link}" target="_blank">WhatsApp</a>`:""}<button class="btn primary" data-save="${esc(r.adventurer_id)}">Salvar</button></div></div></article>`}
async function save(id){const card=document.querySelector(`[data-card="${CSS.escape(id)}"]`),r=rows.find(x=>String(x.adventurer_id)===String(id));if(!card||!r)return;const stage=r.isActive?"customer":card.querySelector('[data-field="pipeline_stage"]').value,follow=card.querySelector('[data-field="next_follow_up_at"]').value,notes=card.querySelector('[data-field="notes"]').value.trim(),state=card.querySelector("[data-state]"),now=new Date().toISOString();state.textContent="Salvando...";const{data:{session}}=await db.auth.getSession();const payload={adventurer_id:id,pipeline_stage:stage,next_follow_up_at:follow?new Date(`${follow}T12:00:00`).toISOString():null,notes:notes||null,updated_at:now,updated_by:session?.user?.id||null};if(stage==="contacted"&&!r.last_contact_at)payload.last_contact_at=now;if(stage==="payment_sent"){payload.payment_status="sent";payload.payment_options_sent_at=r.payment_options_sent_at||now;payload.last_contact_at=now}if(stage==="customer")payload.payment_status="paid";const{error}=await db.from("adventurer_crm").upsert(payload,{onConflict:"adventurer_id"});if(error){console.error(error);state.textContent="Erro ao salvar";state.className="save-state error";return}Object.assign(r,payload);state.textContent="Salvo";state.className="save-state ok";metrics();setTimeout(()=>state.textContent="",1500)}
$("#refreshBtn").onclick=load;$("#searchInput").oninput=render;$("#typeFilter").onchange=render;$("#stageFilter").onchange=render;load();