'use strict';
const SUPABASE_URL='https://gtmngtweohixfeajljik.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_MDNyO5yGhyYJz23QZS-CGw_b0ymShkF';
const PAGE_SIZE=20;
const configured=!SUPABASE_URL.startsWith('YOUR_')&&!SUPABASE_PUBLISHABLE_KEY.startsWith('YOUR_');
const supabase=configured?window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage,storageKey:'evolve-quest-healer-auth'}}):null;
const state={page:1,search:'',stage:'',status:'',level:'',classId:'',activity:'',order:'priority_desc',total:0};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const stageLabel=s=>({welcome:'Boas-vindas pendente',assessment:'Avaliação em andamento',waiting_healer:'Aguardando análise do Healer',dashboard:'Jornada ativa',checkpoint:'Checkpoint disponível',feedback:'Feedback em preparação',progression:'Progressão em andamento'}[s]||'Estado não informado');
function hydrateFromURL(){const p=new URLSearchParams(location.search);state.search=p.get('search')||'';state.stage=p.get('stage')||'';state.status=p.get('status')||'';state.level=p.get('level')||'';state.classId=p.get('classId')||p.get('class_id')||'';state.activity=p.get('activity')||'';state.order=p.get('order')||'priority_desc';state.page=Math.max(1,Number(p.get('page')||1));if($('#searchInput'))$('#searchInput').value=state.search;if($('#stageFilter'))$('#stageFilter').value=state.stage;if($('#statusFilter'))$('#statusFilter').value=state.status;if($('#levelFilter'))$('#levelFilter').value=state.level;if($('#activityFilter'))$('#activityFilter').value=state.activity;if($('#orderFilter'))$('#orderFilter').value=state.order;}
function setStatus(type,msg){$('#statusRegion').innerHTML=`<div class="${type} panel">${type==='loading'?'<div><span class="loading-dot"></span> <span class="loading-dot"></span> <span class="loading-dot"></span></div>':''}<strong>${esc(msg)}</strong>${type==='error'?'<button class="btn btn-secondary" id="retryBtn">Tentar novamente</button>':''}</div>`;if(type==='error')$('#retryBtn')?.addEventListener('click',load);}
function clearStatus(){if($('#statusRegion'))$('#statusRegion').innerHTML='';}
async function authorize(){if(!configured){setStatus('empty','Configure o Supabase para carregar os Aventureiros.');return false;}const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/healer/login/';return false;}const {data:profile,error}=await supabase.from('profiles').select('role,account_status').eq('id',session.user.id).single();if(error||!profile||!['healer','admin'].includes(profile.role)||profile.account_status!=='active'){await supabase.auth.signOut();location.href='/healer/login/';return false;}return true;}
async function loadClasses(){if(!configured)return;const {data}=await supabase.from('adventurer_classes').select('id,name').order('name');const select=$('#classFilter');if(!select)return;(data||[]).forEach(c=>select.insertAdjacentHTML('beforeend',`<option value="${esc(c.id)}">${esc(c.name)}</option>`));select.value=state.classId;}
async function load(){setStatus('loading','Carregando Aventureiros...');if(!(await authorize()))return;const {data,error}=await supabase.rpc('get_healer_adventurers_v2',{p_search:state.search||null,p_stage:state.stage||null,p_status:state.status||null,p_class_id:state.classId||null,p_level:state.level?Number(state.level):null,p_has_alert:state.activity==='alert'?true:null,p_page:state.page,p_page_size:PAGE_SIZE,p_order:state.order});if(error){console.error('[EVOLVE Aventureiros]',error);setStatus('error','Não foi possível carregar os dados agora.');return;}clearStatus();const payload=data||{};const rows=Array.isArray(payload)?payload:(payload.items||[]);state.total=Number(payload.totalCount??payload.total_count??rows[0]?.totalCount??0);render(rows,payload.summary||{});renderPagination();}
function render(rows,summary){$('#resultCount').textContent=`${state.total} resultado${state.total===1?'':'s'}`;updateMetrics(summary);const el=$('#adventurerList');if(!rows.length){el.innerHTML='<div class="empty panel"><strong>Nenhum Aventureiro encontrado.</strong><span class="muted">Ajuste os filtros ou a pesquisa.</span></div>';return;}el.innerHTML=rows.map(a=>`<article class="adventurer-card panel"><div><div class="card-top"><div class="identity"><div class="avatar">${esc((a.displayName||a.fullName||'?').slice(0,2).toUpperCase())}</div><div><h3>${esc(a.displayName||a.fullName||'Aventureiro')}</h3><p class="muted">${esc(a.fullName||'')}</p></div></div><span class="badge ${Number(a.openAlerts||0)>0?'alert':''}">${esc(stageLabel(a.journeyStage))}</span></div></div><div class="card-grid"><div class="datum"><small>Classe e nível</small><strong>${esc(a.className||'Não definida')} · ${a.currentLevel?`Nível ${esc(a.currentLevel)}`:'Nível não definido'}</strong></div><div class="datum"><small>Capítulo</small><strong>${esc(a.chapterTitle||'Não liberado')}</strong></div><div class="datum"><small>Progresso</small><div class="progress" aria-label="${Number(a.chapterProgress||0)}%"><span style="width:${Math.max(0,Math.min(100,Number(a.chapterProgress||0)))}%"></span></div></div><div class="datum"><small>Alertas abertos</small><strong>${Number(a.openAlerts||0)}</strong></div></div><div class="card-actions"><a class="btn btn-primary" href="/healer/aventureiro/?adventurer_id=${encodeURIComponent(a.id)}">Abrir Aventureiro</a></div></article>`).join('');}
function updateMetrics(m){$('#mTotal').textContent=state.total||0;$('#mActive').textContent=Number(m.active||0);$('#mWaiting').textContent=Number(m.waiting||0);$('#mAlerts').textContent=Number(m.alerts||0);$('#mCheckpoints').textContent=Number(m.checkpoints||0);$('#mInactive').textContent=Number(m.inactive||0);}
function renderPagination(){const pages=Math.max(1,Math.ceil(state.total/PAGE_SIZE)),el=$('#pagination');if(pages<=1){el.innerHTML='';return;}let html=`<button ${state.page===1?'disabled':''} data-page="${state.page-1}">‹</button>`;for(let p=Math.max(1,state.page-2);p<=Math.min(pages,state.page+2);p++)html+=`<button data-page="${p}" ${p===state.page?'aria-current="page"':''}>${p}</button>`;html+=`<button ${state.page===pages?'disabled':''} data-page="${state.page+1}">›</button>`;el.innerHTML=html;el.querySelectorAll('button:not([disabled])').forEach(b=>b.onclick=()=>{state.page=Number(b.dataset.page);syncURL();load();});}
function syncURL(){const p=new URLSearchParams();[['search',state.search],['stage',state.stage],['status',state.status],['level',state.level],['classId',state.classId],['activity',state.activity],['order',state.order],['page',state.page>1?state.page:'']].forEach(([k,v])=>{if(v)p.set(k,v)});history.replaceState(null,'',`${location.pathname}${p.toString()?'?'+p:''}`);}
let timer;
function bind(){
 $('#searchInput')?.addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=e.target.value.trim();state.page=1;syncURL();load();},350)});
 $('#clearSearch')&&( $('#clearSearch').onclick=()=>{$('#searchInput').value='';state.search='';state.page=1;syncURL();load();});
 [['stageFilter','stage'],['statusFilter','status'],['levelFilter','level'],['classFilter','classId'],['activityFilter','activity'],['orderFilter','order']].forEach(([id,key])=>$('#'+id)?.addEventListener('change',e=>{state[key]=e.target.value;state.page=1;syncURL();load();}));
 $('#filterToggle')&&( $('#filterToggle').onclick=()=>$('#filtersPanel').classList.toggle('open'));
 $('#menuBtn')&&( $('#menuBtn').onclick=()=>$('#filtersPanel').classList.toggle('open'));
 $('#refreshBtn')&&( $('#refreshBtn').onclick=load);
}
(async()=>{hydrateFromURL();bind();await loadClasses();await load();})();
