'use strict';
const db=window.supabase.createClient('https://gtmngtweohixfeajljik.supabase.co','sb_publishable_MDNyO5yGhyYJz23QZS-CGw_b0ymShkF',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const S=document.querySelector('#status'),Y=document.querySelector('#summary'),R=document.querySelector('#records');
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const d=v=>v?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
const env=v=>v==='gym'?'Academia':v==='home'?'Casa':'—';
const st=v=>({completed:'Concluída',partially_completed:'Parcial',not_completed:'Não concluída'}[v]||v||'—');
(async()=>{try{const {data:{user}}=await db.auth.getUser();if(!user)return location.replace('/login/');const {data,error}=await db.rpc('get_my_mission_registrations');if(error)throw error;render(data||[])}catch(err){console.error(err);S.innerHTML='<strong>Não foi possível carregar seus Registros.</strong>'}})();
function render(items){S.hidden=true;Y.hidden=false;R.hidden=false;const done=items.filter(x=>x.completionStatus==='completed').length;const attention=items.filter(x=>x.requiresHealerAttention).length;Y.innerHTML=`<div class="stat"><span>Registros</span><strong>${items.length}</strong></div><div class="stat"><span>Concluídas</span><strong>${done}</strong></div><div class="stat"><span>Com atenção</span><strong>${attention}</strong></div><div class="stat"><span>Último</span><strong>${items[0]?d(items[0].submittedAt).split(',')[0]:'—'}</strong></div>`;if(!items.length){R.innerHTML='<div class="card"><h2>Nenhum Registro ainda</h2><p class="lead">Depois de concluir uma Missão e enviar seu feedback, ele aparecerá aqui.</p></div>';return}R.innerHTML=items.map(r=>`<article class="card"><div class="record-head"><div><h2 style="margin-bottom:4px">${e(r.missionName)}</h2><div class="lead">${e(r.missionSubtitle||'')} · ${env(r.environment)}</div></div><span class="badge">${st(r.completionStatus)}</span></div><div class="meta-row"><div class="meta"><span>Esforço</span><strong>${r.perceivedEffort??'—'}/10</strong></div><div class="meta"><span>Execução</span><strong>${r.technicalExecution??'—'}/10</strong></div><div class="meta"><span>Data</span><strong>${d(r.submittedAt)}</strong></div></div><div class="notes"><strong>Dor/desconforto:</strong> ${e(r.painStatus||'Não informado')}<br><strong>Estado final:</strong> ${e(r.postMissionFeeling||'Não informado')}${r.generalNotes?`<br><strong>Observação:</strong> ${e(r.generalNotes)}`:''}</div></article>`).join('')}
