
'use strict';
const SUPABASE_URL='https://gtmngtweohixfeajljik.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_MDNyO5yGhyYJz23QZS-CGw_b0ymShkF';
const configured=!SUPABASE_URL.startsWith('YOUR_')&&!SUPABASE_PUBLISHABLE_KEY.startsWith('YOUR_');
const supabase=configured?window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY):null;
const PAGE_SIZE=20;
const state={page:1,search:'',status:'',level:'',order:'priority_desc',total:0,current:null};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function setStatus(type,msg){$('#statusRegion').innerHTML=`<div class="${type} panel"><strong>${esc(msg)}</strong>${type==='error'?'<button id="retryBtn" class="btn btn-secondary">Tentar novamente</button>':''}</div>`;$('#retryBtn')?.addEventListener('click',load)}
async function authorize(){if(!configured){setStatus('empty','Configure o Supabase para carregar as Progressões.');return false}const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/healer/login/';return false}const {data:p,error}=await supabase.from('profiles').select('role,account_status').eq('id',session.user.id).single();if(error||!p||!['healer','admin'].includes(p.role)||p.account_status!=='active'){await supabase.auth.signOut();location.href='/healer/login/';return false}return true}
async function load(){setStatus('loading','Carregando Progressões...');if(!(await authorize()))return;const {data,error}=await supabase.rpc('get_healer_progressions',{p_search:state.search||null,p_status:state.status||null,p_level:state.level?Number(state.level):null,p_page:state.page,p_page_size:PAGE_SIZE,p_order:state.order});if(error){console.error(error);setStatus('error','Não foi possível carregar os dados agora.');return}$('#statusRegion').innerHTML='';const rows=Array.isArray(data)?data:(data?.items||[]);state.total=Number(data?.totalCount??rows[0]?.totalCount??0);render(rows,data?.summary||{});paginate()}
function render(rows,summary){$('#mTotal').textContent=state.total;$('#mFeedback').textContent=summary.awaitingFeedback??0;$('#mProgression').textContent=summary.awaitingProgression??0;$('#mBlocked').textContent=summary.blocked??0;$('#resultCount').textContent=`${state.total} resultado${state.total===1?'':'s'}`;const el=$('#progressionList');if(!rows.length){el.innerHTML='<div class="empty panel"><strong>Nenhuma Progressão pendente.</strong></div>';return}el.innerHTML=rows.map(r=>`<article class="progression-card panel"><div class="card-head"><div class="identity"><div class="avatar">${esc((r.adventurerName||'?').slice(0,2).toUpperCase())}</div><div><h3>${esc(r.adventurerName||'Aventureiro')}</h3><p class="muted">${esc(r.className||'Classe não definida')} · ${r.currentLevel?`Nível ${esc(r.currentLevel)}`:'Nível não definido'}</p></div></div><span class="badge ${r.status==='blocked'?'blocked':r.status==='approved'?'done':'attention'}">${esc(r.statusLabel||r.status||'Status')}</span></div><div class="data-grid"><div class="datum"><small>Capítulo atual</small><strong>${esc(r.chapterTitle||'Não informado')}</strong></div><div class="datum"><small>Próxima ação</small><strong>${esc(r.nextAction||'Abrir Progressão')}</strong></div></div><div class="actions"><button class="btn btn-primary" data-open="${esc(r.id)}">Abrir Progressão</button></div></article>`).join('');el.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.open)))}
async function openDetail(id){$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');$('#drawerTitle').textContent='Carregando ciclo...';$('#drawerBody').innerHTML='<div class="loading panel"><strong>Carregando ciclo...</strong></div>';const {data,error}=await supabase.rpc('get_progression_detail',{p_progression_id:id});if(error){console.error(error);$('#drawerBody').innerHTML='<div class="error panel"><strong>Não foi possível carregar este ciclo.</strong></div>';return}state.current=data;renderDetail(data)}
function renderDetail(d){const p=d.profile||{},cycle=d.cycleSummary||{},feedback=d.feedback||{},progression=d.progression||{},catalog=d.catalog||{};$('#drawerTitle').textContent=p.preferred_name||p.full_name||'Progressão';$('#drawerBody').innerHTML=`
<section class="detail-section panel"><div class="section-head"><h2>Resumo do ciclo</h2></div><div class="kpi-grid"><div class="kpi"><small>Classe atual</small><strong>${esc(cycle.className||'—')}</strong></div><div class="kpi"><small>Nível atual</small><strong>${cycle.currentLevel?`Nível ${esc(cycle.currentLevel)}`:'—'}</strong></div><div class="kpi"><small>Capítulo</small><strong>${esc(cycle.chapterTitle||'—')}</strong></div><div class="kpi"><small>Aderência</small><strong>${esc(cycle.adherencePercentage??'—')}%</strong></div><div class="kpi"><small>Missões concluídas</small><strong>${esc(cycle.missionsCompleted??0)}</strong></div><div class="kpi"><small>Alertas do ciclo</small><strong>${esc(cycle.alertsCount??0)}</strong></div></div></section>
<section class="detail-section panel"><div class="section-head"><h2>Feedback de Evolução</h2></div><div class="step-grid two"><div class="field"><label for="publicSummary">Resumo visível ao Aventureiro</label><textarea id="publicSummary">${esc(feedback.public_summary||'')}</textarea></div><div class="field"><label for="achievements">Conquistas</label><textarea id="achievements">${esc(feedback.achievements||'')}</textarea></div><div class="field"><label for="recommendations">Recomendações</label><textarea id="recommendations">${esc(feedback.next_cycle_recommendations||'')}</textarea></div><div class="field"><label for="internalNotes">Notas internas do Healer</label><textarea id="internalNotes">${esc(feedback.internal_notes||'')}</textarea></div></div></section>
<section class="detail-section panel"><div class="section-head"><h2>Decisão de Progressão</h2></div><div class="step-grid two"><div class="field"><label for="decisionType">Decisão principal</label><select id="decisionType"><option value="">Selecione</option><option value="stay_current_chapter">Manter no Capítulo atual</option><option value="advance_chapter">Avançar para o próximo Capítulo</option><option value="change_level">Alterar Nível</option><option value="change_class">Alterar Classe</option><option value="pause">Pausar Progressão</option><option value="require_complementary_assessment">Solicitar avaliação complementar</option><option value="require_medical_clearance">Solicitar liberação médica</option><option value="complete_journey">Encerrar Jornada</option></select></div><div class="field"><label for="decisionReason">Justificativa</label><textarea id="decisionReason">${esc(progression.decision_reason||'')}</textarea></div><div class="field"><label for="newClass">Nova Classe</label><select id="newClass"><option value="">Manter atual</option>${(catalog.classes||[]).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label for="newLevel">Novo Nível</label><select id="newLevel"><option value="">Manter atual</option>${[1,2,3,4,5].map(n=>`<option value="${n}">Nível ${n}</option>`).join('')}</select></div><div class="field"><label for="newChapter">Próximo Capítulo</label><select id="newChapter"><option value="">Selecione</option>${(catalog.chapters||[]).map(c=>`<option value="${esc(c.id)}">${esc(c.chapter_number)} — ${esc(c.title)}</option>`).join('')}</select></div><div class="field"><label for="frequency">Frequência recomendada</label><select id="frequency">${[1,2,3,4,5].map(n=>`<option value="${n}">${n} sessões por semana</option>`).join('')}</select></div></div></section>
<section class="detail-section panel"><div class="section-head"><h2>Missões do próximo ciclo</h2></div><div class="mission-grid">${(catalog.missions||[]).map(m=>`<div class="mission-option"><label><input type="checkbox" name="mission" value="${esc(m.id)}"><span><strong>${esc(m.mission_type)} — ${esc(m.environment)}</strong><br><span class="muted">${esc(m.name)}</span></span></label></div>`).join('')||'<div class="empty"><strong>Nenhuma Missão disponível.</strong></div>'}</div></section>
<section class="detail-section panel"><div class="actions"><button class="btn btn-secondary" id="saveDraftBtn">Salvar rascunho</button><button class="btn btn-primary" id="reviewBtn">Revisar Progressão</button></div></section>`;
$('#decisionType').value=progression.decision_type||'';$('#newClass').value=progression.new_class_id||'';$('#newLevel').value=progression.new_level||'';$('#newChapter').value=progression.new_chapter_id||'';$('#frequency').value=progression.recommended_frequency||3;(progression.mission_ids||[]).forEach(id=>document.querySelector(`input[name="mission"][value="${CSS.escape(id)}"]`)?.setAttribute('checked','checked'));$('#saveDraftBtn').onclick=saveDraft;$('#reviewBtn').onclick=openReview}
function collect(){return{progression_id:state.current?.progression?.id,feedback:{public_summary:$('#publicSummary').value.trim(),achievements:$('#achievements').value.trim(),next_cycle_recommendations:$('#recommendations').value.trim(),internal_notes:$('#internalNotes').value.trim()},decision_type:$('#decisionType').value,decision_reason:$('#decisionReason').value.trim(),new_class_id:$('#newClass').value||null,new_level:$('#newLevel').value?Number($('#newLevel').value):null,new_chapter_id:$('#newChapter').value||null,recommended_frequency:Number($('#frequency').value),mission_ids:[...document.querySelectorAll('input[name="mission"]:checked')].map(x=>x.value)}}
async function saveDraft(){const payload=collect();const {error:e1}=await supabase.rpc('save_evolution_feedback',{p_progression_id:payload.progression_id,p_feedback:payload.feedback});if(e1){alert('Não foi possível salvar o Feedback.');return}const {error:e2}=await supabase.rpc('save_progression_draft',{p_progression_id:payload.progression_id,p_progression:payload});if(e2){alert('Não foi possível salvar a Progressão.');return}alert('Progressão salva como rascunho.')}
function openReview(){const p=collect();if(!p.decision_type||!p.decision_reason){alert('Selecione a decisão e informe a justificativa.');return}if(!p.mission_ids.length&&!['require_complementary_assessment','require_medical_clearance','complete_journey','pause'].includes(p.decision_type)){alert('Selecione as Missões do próximo ciclo.');return}$('#reviewModal').classList.add('open');$('#reviewModal').setAttribute('aria-hidden','false');$('#reviewBody').innerHTML=`<div class="review-list"><div class="review-row"><span>Aventureiro</span><strong>${esc(state.current?.profile?.preferred_name||state.current?.profile?.full_name||'—')}</strong></div><div class="review-row"><span>Decisão</span><strong>${esc(p.decision_type)}</strong></div><div class="review-row"><span>Novo nível</span><strong>${esc(p.new_level||'Manter')}</strong></div><div class="review-row"><span>Missões</span><strong>${p.mission_ids.length}</strong></div></div><p class="muted">Ao confirmar, o ciclo atual será encerrado e o novo ciclo será liberado para o Aventureiro.</p><button class="btn btn-primary" id="confirmBtn">Confirmar Progressão e liberar novo ciclo</button>`;$('#confirmBtn').onclick=confirmProgression}
async function confirmProgression(){const payload=collect();await saveDraft();$('#confirmBtn').disabled=true;$('#confirmBtn').textContent='Validando novo ciclo...';const {data,error}=await supabase.rpc('complete_journey_progression',{p_progression_id:payload.progression_id});if(error){console.error(error);alert('Não foi possível concluir esta ação agora.');$('#confirmBtn').disabled=false;$('#confirmBtn').textContent='Confirmar Progressão e liberar novo ciclo';return}alert('Novo ciclo liberado com sucesso.');location.href=data?.adventurerId?`/healer/aventureiro/?adventurer_id=${encodeURIComponent(data.adventurerId)}`:'/healer/painel/'}
function paginate(){const pages=Math.max(1,Math.ceil(state.total/PAGE_SIZE)),el=$('#pagination');if(pages<=1){el.innerHTML='';return}el.innerHTML=`<button ${state.page===1?'disabled':''} data-page="${state.page-1}">‹</button><button aria-current="page">${state.page}</button><button ${state.page===pages?'disabled':''} data-page="${state.page+1}">›</button>`;el.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=Number(b.dataset.page);load()})}
let timer;$('#searchInput').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=e.target.value.trim();state.page=1;load()},350)});$('#statusFilter').onchange=e=>{state.status=e.target.value;state.page=1;load()};$('#levelFilter').onchange=e=>{state.level=e.target.value;state.page=1;load()};$('#orderFilter').onchange=e=>{state.order=e.target.value;state.page=1;load()};$('#filterToggle').onclick=()=>$('#filtersPanel').classList.toggle('open');$('#refreshBtn').onclick=load;$('#closeDrawer').onclick=()=>{$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true')};$('#closeReview').onclick=()=>{$('#reviewModal').classList.remove('open');$('#reviewModal').setAttribute('aria-hidden','true')};load();
