'use strict';
const db=window.supabase.createClient('https://gtmngtweohixfeajljik.supabase.co','sb_publishable_MDNyO5yGhyYJz23QZS-CGw_b0ymShkF',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmtDate=v=>v?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(v)):'';
const CHARACTERS=[{id:'warrior-m',name:'Guerreiro',gender:'Masculino',className:'sprite-warrior-m'},{id:'warrior-f',name:'Guerreira',gender:'Feminino',className:'sprite-warrior-f'},{id:'mage-m',name:'Mago',gender:'Masculino',className:'sprite-mage-m'},{id:'mage-f',name:'Maga',gender:'Feminino',className:'sprite-mage-f'},{id:'vampire-m',name:'Vampiro',gender:'Masculino',className:'sprite-vampire-m'},{id:'vampire-f',name:'Vampira',gender:'Feminino',className:'sprite-vampire-f'},{id:'bard-m',name:'Bardo',gender:'Masculino',className:'sprite-bard-m'},{id:'bard-f',name:'Barda',gender:'Feminino',className:'sprite-bard-f'}];
let selectedCharacterId=localStorage.getItem('evolveQuestCharacter')||'warrior-m',journeyData=null;
(async()=>{try{const {data:{user},error:userError}=await db.auth.getUser();if(userError||!user)return location.replace('/login/');const {data,error}=await db.rpc('get_my_journey_map');if(error)throw error;journeyData=data||{};render(journeyData)}catch(error){console.error('[EVOLVE Jornada 8-bit v3]',error);$('status').classList.add('error');$('status').innerHTML='<strong>Não foi possível carregar sua Jornada.</strong><span>A Jornada atual continua disponível normalmente.</span>'}})();
function currentCharacter(){return CHARACTERS.find(c=>c.id===selectedCharacterId)||CHARACTERS[0]}
function render(data){const p=data.profile||{},j=data.journey||{},c=data.chapter||{},s=data.summary||{};const progress=Math.max(0,Math.min(100,Number(j.chapterProgress||0))),totalXp=Number(j.totalXp||0),planned=Math.max(1,Number(j.plannedSessions||0)||8),completed=Math.max(0,Number(j.completedSessions||0)),level=Number(p.currentLevel||1);$('status').hidden=true;$('journeyContent').hidden=false;$('headerName').textContent=p.preferredName||p.fullName||'Aventureiro';$('headerLevel').textContent=`Nível ${level}`;$('headerXp').textContent=`${totalXp} XP`;$('chapterTitle').textContent=`Capítulo ${c.number||''} · ${c.title||'Jornada Atual'}`;$('chapterObjective').textContent=c.objective||'Continue avançando em sua Jornada.';$('progressText').textContent=`${progress}%`;$('progressBar').style.width=`${progress}%`;$('sessionsLabel').textContent=`${completed} de ${planned} sessões`;$('mapSessionsLabel').textContent=`${completed} de ${planned} sessões`;const milestone=s.nextMilestone||'Continue avançando';$('nextMilestone').textContent=milestone;$('nextMilestoneTitle').textContent=milestone;$('nextMilestoneText').textContent=nextText(progress,data.checkpoint);$('className').textContent=p.className||'—';$('frequency').textContent=j.prescribedFrequency?`${j.prescribedFrequency}x / semana`:'—';$('streak').textContent=j.currentStreak?`${j.currentStreak} dias`:'0 dias';$('totalXp').textContent=`${totalXp} XP`;$('levelNumber').textContent=level;$('xpBar').style.width=`${Math.min(100,(totalXp%1000)/10)}%`;renderCharacters();renderMap(planned,completed);renderDots(planned,completed);renderMiniAchievements(data.achievements||[]);renderAchievements(data.achievements||[]);renderRecords(data.records||[]);renderDialog(data)}
function nextText(p,cp){if(p<25)return'Complete novas sessões para alcançar o primeiro grande marco.';if(p<50)return'Você já passou do primeiro quarto. Continue avançando.';if(p<75)return'A metade ficou para trás. O próximo marco está próximo.';if(p<100)return'A reta final começou. Falta pouco para fechar o Capítulo.';if(cp?.status!=='completed')return'O Capítulo está completo. O próximo portal é o Checkpoint.';return'Seu ciclo atual foi concluído. Aguarde a próxima progressão.'}
function renderCharacters(){const ch=currentCharacter();$('selectedSprite').className=`sprite ${ch.className}`;$('selectedHeroName').textContent=ch.name;$('selectedHeroGender').textContent=ch.gender;$('characterGrid').innerHTML=CHARACTERS.map(c=>`<button class="character-card ${c.id===selectedCharacterId?'selected':''}" type="button" data-character="${c.id}"><div class="sprite ${c.className}"></div><span>${esc(c.name)}</span></button>`).join('');$('characterGrid').querySelectorAll('[data-character]').forEach(btn=>btn.addEventListener('click',()=>{selectedCharacterId=btn.dataset.character;localStorage.setItem('evolveQuestCharacter',selectedCharacterId);renderCharacters();if(journeyData){const j=journeyData.journey||{};renderMap(Math.max(1,Number(j.plannedSessions||0)||8),Math.max(0,Number(j.completedSessions||0)))}}))}
$('toggleCharacters').addEventListener('click',()=>{$('characterGrid').hidden=!$('characterGrid').hidden});
function mapPoints(count){const a=[{x:15,y:70},{x:27,y:66},{x:38,y:55},{x:49,y:62},{x:60,y:51},{x:70,y:57},{x:80,y:46},{x:87,y:35},{x:78,y:28},{x:65,y:34},{x:54,y:28},{x:43,y:36},{x:32,y:28},{x:23,y:36},{x:15,y:30},{x:10,y:20}];return a.slice(0,count)}
function renderMap(planned,completed){const nodeCount=Math.max(4,Math.min(16,planned)),points=mapPoints(nodeCount),currentIndex=Math.max(0,Math.min(nodeCount-1,completed)),layer=$('pathLayer');layer.innerHTML='';points.forEach((p,i)=>{if(i<points.length-1){const n=points[i+1],dx=n.x-p.x,dy=n.y-p.y,dist=Math.sqrt(dx*dx+dy*dy),angle=Math.atan2(dy,dx)*180/Math.PI,seg=document.createElement('span');seg.className='path-segment';seg.style.left=`${p.x}%`;seg.style.top=`${p.y}%`;seg.style.width=`${dist}%`;seg.style.transform=`rotate(${angle}deg)`;layer.appendChild(seg)}const node=document.createElement('span');node.className=`path-node ${i<currentIndex?'complete':i===currentIndex?'current':'locked'}`;node.style.left=`${p.x}%`;node.style.top=`${p.y}%`;node.textContent=i<currentIndex?'✓':i+1;layer.appendChild(node)});const hero=$('heroMarker'),p=points[currentIndex]||points[0];hero.style.left=`calc(${p.x}% - 26px)`;hero.style.top=`calc(${p.y}% - 74px)`;hero.innerHTML=`<div class="sprite ${currentCharacter().className}"></div>`}
function renderDots(planned,completed){const count=Math.max(4,Math.min(16,planned));$('mapProgressDots').innerHTML=Array.from({length:count},(_,i)=>`<span class="${i<completed?'complete':i===completed?'current':''}"></span>`).join('')}
function renderMiniAchievements(items){const unlocked=items.filter(a=>a.unlocked).slice(-3).reverse();$('achievementMiniList').innerHTML=unlocked.length?unlocked.map(a=>`<div class="mini-achievement"><i>◆</i><div><strong>${esc(a.title)}</strong><span>${esc(a.description)}</span></div><b>✓</b></div>`).join(''):'<div class="empty">Sua primeira conquista aparecerá aqui.</div>'}
function renderAchievements(items){$('achievements').innerHTML=items.map(a=>`<article class="achievement ${a.unlocked?'unlocked':'locked'}"><div class="icon">${a.unlocked?'🏆':'🔒'}</div><strong>${esc(a.title)}</strong><p>${esc(a.description)}</p></article>`).join('')}
function renderRecords(items){const visible=items.slice(0,5);if(!visible.length){$('recentRecords').innerHTML='<div class="empty">Sua primeira missão registrada aparecerá aqui.</div>';return}$('recentRecords').innerHTML=visible.map(r=>`<article class="record"><div class="record-mark">${r.completionStatus==='completed'?'✓':'•'}</div><div><strong>${esc(r.missionName||'Missão')}</strong><span>${esc(r.missionSubtitle||'')}${r.environment?` · ${r.environment==='gym'?'Academia':r.environment==='home'?'Casa':'Missão'}`:''}</span></div><time>${fmtDate(r.submittedAt)}</time></article>`).join('')}
function renderDialog(data){const j=data.journey||{},achievements=Array.isArray(data.achievements)?data.achievements:[],records=Array.isArray(data.records)?data.records:[],recentUnlocked=[...achievements].reverse().find(a=>a.unlocked),xp=Number(j.totalXp||0);let title='Mais um passo, Aventureiro!',text='Cada missão concluída te deixa mais forte e aproxima você do próximo marco.',reward=xp?`${xp} XP acumulados`:'';if(recentUnlocked){title=`${recentUnlocked.title}!`;text=recentUnlocked.description||'Uma nova conquista foi adicionada à sua Jornada.';reward='CONQUISTA DESBLOQUEADA'}else if(records.length){title='Sua Jornada continua!';text='Seu último Registro da Missão já faz parte do percurso. Continue mantendo a consistência.'}$('dialogTitle').textContent=title;$('dialogText').textContent=text;$('dialogReward').textContent=reward}
window.addEventListener('resize',()=>{if(!journeyData)return;const j=journeyData.journey||{};renderMap(Math.max(1,Number(j.plannedSessions||0)||8),Math.max(0,Number(j.completedSessions||0)))})
