
'use strict';
const SUPABASE_URL='https://gtmngtweohixfeajljik.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_MDNyO5yGhyYJz23QZS-CGw_b0ymShkF';
const configured=!SUPABASE_URL.startsWith('YOUR_')&&!SUPABASE_PUBLISHABLE_KEY.startsWith('YOUR_');
const supabase=configured?window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage,storageKey:'evolve-quest-healer-auth'}}):null;
const PAGE_SIZE=20,state={page:1,search:'',period:'',status:'',order:'priority_desc',total:0};
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function setStatus(type,msg){$('#statusRegion').innerHTML=`<div class="${type} panel"><strong>${esc(msg)}</strong>${type==='error'?'<button id="retryBtn" class="btn btn-secondary">Tentar novamente</button>':''}</div>`;$('#retryBtn')?.addEventListener('click',load)}
async function authorize(){if(!configured){setStatus('empty','Configure o Supabase para carregar os dados.');return false}const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/healer/login/';return false}const {data:p,error}=await supabase.from('profiles').select('role,account_status').eq('id',session.user.id).single();if(error||!p||!['healer','admin'].includes(p.role)||p.account_status!=='active'){await supabase.auth.signOut();location.href='/healer/login/';return false}return true}
async function load(){setStatus('loading','Carregando Registros...');if(!(await authorize()))return;const {data,error}=await supabase.rpc('get_healer_registrations',{p_search:state.search||null,p_period:state.period||null,p_status:state.status||null,p_page:state.page,p_page_size:PAGE_SIZE,p_order:state.order});if(error){console.error(error);setStatus('error','Não foi possível carregar os dados agora.');return}$('#statusRegion').innerHTML='';const rows=Array.isArray(data)?data:(data?.items||[]);state.total=Number(data?.totalCount??rows[0]?.totalCount??0);render(rows,data?.summary||{});paginate()}
function render(rows,summary){$('#mTotal').textContent=state.total;$('#mPending').textContent=summary.pending??0;$('#mAttention').textContent=summary.attention??0;$('#mDone').textContent=summary.done??0;const el=$('#list');if(!rows.length){el.innerHTML='<div class="empty panel"><strong>Nenhum Registro encontrado.</strong></div>';return}el.innerHTML=rows.map(r=>card(r)).join('');el.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.open)))}
function card(r){const name=r.adventurerName||r.displayName||'Aventureiro';return `<article class="item panel"><div class="item-head"><div class="identity"><div class="avatar">${esc(name.slice(0,2).toUpperCase())}</div><div><h3>${esc(name)}</h3><p class="muted">${esc(r.subtitle||r.missionName||r.chapterTitle||'')}</p></div></div><span class="badge ${r.severity==='high'||r.severity==='critical'?'danger':r.requiresAttention?'alert':r.status==='resolved'||r.status==='completed'?'success':''}">${esc(r.statusLabel||r.status||'Status')}</span></div><div class="data-grid"><div class="datum"><small>Data</small><strong>${esc(r.dateLabel||r.submittedAt||r.createdAt||'—')}</strong></div><div class="datum"><small>Prioridade</small><strong>${esc(r.priorityLabel||r.severityLabel||'Regular')}</strong></div></div><div class="actions"><button class="btn btn-primary" data-open="${esc(r.id)}">Abrir detalhe</button><a class="btn btn-secondary" href="/healer/aventureiro/?adventurer_id=${encodeURIComponent(r.adventurerId||'')}">Aventureiro</a></div></article>`}
async function openDetail(id){$('#drawer').classList.add('open');$('#detailTitle').textContent='Carregando...';$('#detailBody').innerHTML='<div class="loading panel"><strong>Carregando detalhe...</strong></div>';const {data,error}=await supabase.rpc('get_healer_registration_detail',{p_registration_id:id});if(error){$('#detailBody').innerHTML='<div class="error panel"><strong>Este recurso não está disponível.</strong></div>';return}renderDetail(data)}
function renderDetail(d){$('#detailTitle').textContent=d.title||d.missionName||d.adventurerName||'Detalhe';$('#detailBody').innerHTML=`<section class="detail-section panel"><div class="section-head"><h2>Resumo</h2></div><div class="stack">${Object.entries(d.summary||{}).map(([k,v])=>`<div class="row"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')||'<p class="muted">Nenhum resumo disponível.</p>'}</div></section>${detailActions(d)}</section>`}
function detailActions(d){if('registros'==='alertas')return `<section class="detail-section panel"><h2>Ações do alerta</h2><div class="field"><label for="actionNote">Nota</label><textarea id="actionNote"></textarea></div><div class="actions"><button class="btn btn-secondary" onclick="updateAlert('${esc(d.id)}','viewed')">Marcar visualizado</button><button class="btn btn-secondary" onclick="updateAlert('${esc(d.id)}','in_progress')">Iniciar acompanhamento</button><button class="btn btn-primary" onclick="updateAlert('${esc(d.id)}','resolved')">Resolver</button><button class="btn btn-danger" onclick="updateAlert('${esc(d.id)}','dismissed')">Descartar</button></div></section>`;if('registros'==='checkpoints')return `<section class="detail-section panel"><h2>Análise do Healer</h2><div class="field"><label for="reviewNote">Observações internas</label><textarea id="reviewNote"></textarea></div><div class="actions"><button class="btn btn-primary">Salvar análise</button><a class="btn btn-secondary" href="/healer/progressao/?checkpoint_id=${encodeURIComponent(d.id||'')}">Ir para Progressão</a></div></section>`;return `<section class="detail-section panel"><h2>Observação interna</h2><div class="field"><label for="registrationNote">Nota do Healer</label><textarea id="registrationNote"></textarea></div><button class="btn btn-primary">Salvar observação</button></section>`}
window.updateAlert=async(id,status)=>{const note=$('#actionNote')?.value.trim()||'';if(['resolved','dismissed'].includes(status)&&!note){alert('Informe uma justificativa ou nota.');return}const {error}=await supabase.rpc('update_healer_alert_status',{p_alert_id:id,p_status:status,p_note:note});if(error){alert('Não foi possível concluir esta ação agora.');return}alert(status==='resolved'?'Alerta resolvido com sucesso.':'Status atualizado com sucesso.');openDetail(id);load()};
function paginate(){const pages=Math.max(1,Math.ceil(state.total/PAGE_SIZE)),el=$('#pagination');if(pages<=1){el.innerHTML='';return}el.innerHTML=`<button ${state.page===1?'disabled':''} data-p="${state.page-1}">‹</button><button aria-current="page">${state.page}</button><button ${state.page===pages?'disabled':''} data-p="${state.page+1}">›</button>`;el.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{state.page=Number(b.dataset.p);load()})}
let timer;$('#searchInput').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=e.target.value.trim();state.page=1;load()},350)});$('#periodFilter').onchange=e=>{state.period=e.target.value;state.page=1;load()};$('#statusFilter').onchange=e=>{state.status=e.target.value;state.page=1;load()};$('#orderFilter').onchange=e=>{state.order=e.target.value;state.page=1;load()};$('#filterToggle').onclick=()=>$('#filtersPanel').classList.toggle('open');$('#refreshBtn').onclick=load;$('#closeDrawer').onclick=()=>$('#drawer').classList.remove('open');$('#drawer').addEventListener('click',e=>{if(e.target===$('#drawer'))$('#drawer').classList.remove('open')});load();
