
'use strict';
const SUPABASE_URL='https://gtmngtweohixfeajljik.supabase.co',SUPABASE_PUBLISHABLE_KEY='sb_publishable_MDNyO5yGhyYJz23QZS-CGw_b0ymShkF';
const configured=!SUPABASE_URL.startsWith('YOUR_')&&!SUPABASE_PUBLISHABLE_KEY.startsWith('YOUR_');
const supabase=configured?window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY):null;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const params=new URLSearchParams(location.search),adventurerId=params.get('adventurer_id')||location.pathname.split('/').filter(Boolean).at(-1);
function setStatus(type,msg){$('#statusRegion').innerHTML=`<div class="${type} panel"><strong>${esc(msg)}</strong></div>`}
async function authorize(){if(!configured){setStatus('empty','Configure o Supabase para carregar este perfil.');return false;}const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/healer/login/';return false;}const {data:p,error}=await supabase.from('profiles').select('role,account_status').eq('id',session.user.id).single();if(error||!p||!['healer','admin'].includes(p.role)||p.account_status!=='active'){await supabase.auth.signOut();location.href='/healer/login/';return false;}return true}
async function load(){setStatus('loading','Carregando a Jornada deste Aventureiro...');if(!adventurerId){setStatus('error','Aventureiro não encontrado.');return}if(!(await authorize()))return;const {data,error}=await supabase.rpc('get_healer_adventurer_detail',{p_adventurer_id:adventurerId});if(error){console.error(error);setStatus('error',error.code==='42501'?'Você não possui permissão para visualizar este Aventureiro.':'Não foi possível carregar os dados agora.');return}if(!data){setStatus('empty','Aventureiro não encontrado.');return}$('#statusRegion').innerHTML='';render(data)}
function fmtDate(v){if(!v)return'Não informado';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium'}).format(new Date(v))}
function render(d){const p=d.profile||{},j=d.journey||{},c=d.class||{},ch=d.chapter||{};$('#pageTitle').textContent=p.preferred_name||p.full_name||'Aventureiro';const hero=$('#profileHero');hero.classList.remove('hidden');hero.innerHTML=`<div class="profile-title"><div class="avatar">${esc((p.preferred_name||p.full_name||'?').slice(0,2).toUpperCase())}</div><div><h2>${esc(p.preferred_name||p.full_name||'Aventureiro')}</h2><p class="muted">${esc(p.full_name||'')} · ${esc(p.email||'')}</p></div></div><div class="meta-row"><span class="badge">${esc(p.journey_stage||'Estado não informado')}</span><span class="badge">${esc(p.account_status||'Status não informado')}</span><span class="badge">${esc([p.city,p.state].filter(Boolean).join(' · ')||'Local não informado')}</span></div>`;
$('#detailGrid').innerHTML=`
<section class="section panel" data-section="overview"><div class="section-head"><h2>Estado atual</h2></div><div class="kpi-grid"><div class="kpi"><small>Classe</small><strong>${esc(c.name||'Não definida')}</strong></div><div class="kpi"><small>Nível</small><strong>${j.current_level?`Nível ${esc(j.current_level)}`:'Não definido'}</strong></div><div class="kpi"><small>Capítulo</small><strong>${esc(ch.title||'Não liberado')}</strong></div><div class="kpi"><small>Progresso</small><strong>${Number(j.chapter_progress||0)}%</strong></div><div class="kpi"><small>Sequência</small><strong>${Number(j.current_streak||0)} dias</strong></div><div class="kpi"><small>Início da Jornada</small><strong>${fmtDate(j.started_at)}</strong></div></div></section>
<section class="section panel"><div class="section-head"><h2>Próxima ação</h2></div><p>${esc(d.recommendedAction?.label||'Nenhuma ação prioritária no momento.')}</p>${d.recommendedAction?.url?`<a class="btn btn-primary" href="${esc(d.recommendedAction.url)}">Abrir módulo</a>`:''}</section>
<section class="section panel wide" data-section="missions"><div class="section-head"><h2>Missões prescritas</h2></div><div class="stack">${(d.missions||[]).length?(d.missions||[]).map(m=>`<div class="row-item"><div><strong>${esc(m.name||m.mission_type)}</strong><p class="muted">${esc(m.environment||'')} · ${esc(m.status||'')}</p></div><a class="btn btn-secondary" href="/healer/aventureiros/${encodeURIComponent(adventurerId)}/missoes/">Ver Missão</a></div>`).join(''):'<div class="empty"><strong>Nenhuma Missão prescrita no Capítulo atual.</strong></div>'}</div></section>
<section class="section panel" data-section="registrations"><div class="section-head"><h2>Registros recentes</h2></div><div class="stack">${(d.recentRegistrations||[]).length?d.recentRegistrations.slice(0,5).map(r=>`<div class="row-item"><div><strong>${esc(r.mission_name||'Missão')}</strong><p class="muted">${fmtDate(r.submitted_at)} · esforço ${esc(r.perceived_effort??'—')} · dor ${esc(r.pain_status??'—')}</p></div><a class="btn btn-secondary" href="/healer/registros/${encodeURIComponent(r.id)}/">Abrir</a></div>`).join(''):'<div class="empty"><strong>Nenhum Registro da Missão enviado.</strong></div>'}</div></section>
<section class="section panel" data-section="alerts"><div class="section-head"><h2>Alertas</h2></div><div class="stack">${(d.alerts||[]).length?d.alerts.map(a=>`<div class="row-item"><div><strong>${esc(a.title||'Alerta')}</strong><p class="muted">${esc(a.severity||'')} · ${fmtDate(a.created_at)}</p></div><a class="btn btn-secondary" href="/healer/alertas/${encodeURIComponent(a.id)}/">Abrir alerta</a></div>`).join(''):'<div class="empty"><strong>Nenhum alerta aberto.</strong></div>'}</div></section>
<section class="section panel"><div class="section-head"><h2>Checkpoint</h2></div>${d.checkpoint?`<div class="kpi-grid"><div class="kpi"><small>Status</small><strong>${esc(d.checkpoint.status)}</strong></div><div class="kpi"><small>Vencimento</small><strong>${fmtDate(d.checkpoint.due_at)}</strong></div></div><a class="btn btn-secondary" href="/healer/checkpoints/${encodeURIComponent(d.checkpoint.id)}/">Abrir Checkpoint</a>`:'<div class="empty"><strong>Nenhum Checkpoint disponível.</strong></div>'}</section>
<section class="section panel wide" data-section="history"><div class="section-head"><h2>Histórico resumido</h2></div><div class="timeline">${(d.recentTimeline||[]).length?d.recentTimeline.map(e=>`<div class="event"><strong>${esc(e.label||e.action)}</strong><p class="muted">${fmtDate(e.created_at)}</p></div>`).join(''):'<div class="empty"><strong>Nenhum evento disponível.</strong></div>'}</div></section>`;
}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const target=document.querySelector(`[data-section="${b.dataset.target}"]`);target?.scrollIntoView({behavior:'smooth',block:'start'})});load();
